### ISSUE TITLE
Experimenting with trying to keep Asana as our main todo.

### ISSUE THREAD

**Issue by jonleung** [hackedu/discussions#1]
1) There is a lot of private information inside of my task list that I can't make public
2) I think the collaboration features in Asana are better than a plain text file, i.e. the log of what has happened. I think there will be too much overhead with git.

One big blocking feature seems to be not being able to see other people's tasks. What if we put everything into projects that people can see. We can try to keep using Asana until it blocks again?

I'm happy to answer all the Asana questions and checkin with everyone to make sure things are working properly in Asana. Please bring up any blocking issues you notice in standups.

@zachlatta @MaxWofford @benzweig

**Comment by zachlatta** [comment]
> 1) There is a lot of private information inside of my task list that I can't make public

Perhaps maintain a private task list as well?

> 2) I think the collaboration features in Asana are better than a plain text file, i.e. the log of what has happened. I think there will be too much overhead with git.

What about GitHub issues?

> One big blocking feature seems to be not being able to see other people's tasks. What if we put everything into projects that people can see. We can try to keep using Asana until it blocks again?

Doesn't this make the process of adding tasks significantly more arduous? It adds two additional taps and typing (selecting the project to add the task to and assigning the task to myself) to the mobile app. It also requires an additional step of adding every task we create to our personal project from the web interface—we may forget to do this, similar to how we forgot to mark every task we create as public.

What are your thoughts on using GitHub issues?

**Comment by zachlatta** [comment]
One more thing: I spent the last two hours taking a break and learning Emacs and org-mode. Some really cool stuff, I may want to experiment with using org-mode as a TODO system. There seems to be an [integration](http://orgmode.org/worg/org-contrib/gsoc2012/student-projects/org-sync/) for syncing it with GitHub issues, which may solve the problem of prioritization.

**Comment by jonleung** [comment]
i think the most important thing for us to do is to set an objective to what order of things we want in a collaboration system.

whar do you guys think are the order of importance of features a todo list system should have. Until we decide on a new one, we should be actively maintaining our current system.

**Comment by jonleung** [comment]
So Safari crashed and lost the detailed response, took me like 15 minutes to type it and I wasn't finished. And the feedback loop was too long. I feel a conversation may be more time effective in discussing these larger issues. In the mean time, let's be diligent in using the current system.

**Comment by zachlatta** [comment]
We concluded offline that we'd use GitHub issues as our primary todo, but Asana can be used as a personal todo system by members of the team.
