### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by jonleung** [hackedu/discussions#2]
I think this could be a great alternative to have threaded discussions rather than IRC.
- We can create an issue for an issues we have and it won't get lost in the ether
- It is also completely public
- People also get notifications

What are your thoughts @benzweig @zachlatta @MaxWofford?

**Comment by MaxWofford** [comment]
:+1: Open to trying it out!

**Comment by zachlatta** [comment]
Yup! Open as well. I think this is a good format for long-term discussions and IRC is good for impromptu stuff.

**Comment by jonleung** [comment]
Awesome, closing the issue for now!
