### ISSUE TITLE
Commitments

### ISSUE THREAD

**Issue by jonleung** [hackedu/discussions#3]
What are your thoughts on keeping a list of commitments here in this thread or perhaps in a file in this repo?

Some of our commitments so far. What are the other ones?

1. When we say something we are going to do it.
2. Daily stand ups before 12:30pm
	a. Every day, @zrl, @jonl, @maxw are going to post in #hack-edu stand ups before noon with what they did yesterday, what they're going to do today, and what they're blocking on Will be on time to all events including internal and external meetings, physical or virtual.

@zachlatta @MaxWofford

**Comment by MaxWofford** [comment]
You just tagged other people:
https://github.com/zrl
https://github.com/jonl
https://github.com/maxw

**Comment by maxw** [comment]
I think you added the wrong person to this ;)

Max

**Comment by zachlatta** [comment]
Sorry about that @maxw! @MaxWofford has your handle in our IRC channel :-P.

Quick correction, we're posting in #hackedu, not #hack-edu in Freenode :-).

I'm not sure if it makes sense to always say what I'm blocking on in my standup. I don't think I'll have something for that everyday. Happy to experiment with keeping a list here, but I won't actively maintain it from my end. If the goal is integrity, what is the benefit of maintaining a list of everything we've committed to? Sounds like a similar accountability mechanism to the dollar bill stuff.

**Comment by jonleung** [comment]
Ok sounds reasonable. My hypothesis is that sometimes we commit to things and they fall through, this was an attempt at resolving this. Let's just try verbal commitments for now until they become a blocking issue. This means being ok time for things : )

**Comment by jonleung** [comment]
Ok sounds reasonable. My hypothesis is that sometimes we commit to things and they fall through, this was an attempt at resolving this. Let's just try verbal commitments for now until they become a blocking issue. This means being ok time for things which has been a blocking issue for me and it seems all of us as well.

**Comment by zrl** [comment]
I think you added the wrong zrl, too...

Zachary Levin

**Comment by maxw** [comment]
Will you remove me from this?

**Comment by zachlatta** [comment]
Sorry about this @zrl and @maxw. You can unsubscribe yourselves from this thread by clicking this button on the upper right of this issue:

![tmp](https://cloud.githubusercontent.com/assets/992248/7050329/82e4df74-ddd5-11e4-8ac0-5a45c3d67e8c.png)

**Comment by zachlatta** [comment]
Closing due to the introduction of https://github.com/hackedu/pm.
