### ISSUE TITLE
501(c)3 Application

### ISSUE THREAD

**Issue by jonleung** [hackedu/discussions#9]
I think it is important for us to start this now. We should initially figure out what all the forms are and everything, then setup a time with Tyler write it together. Then after that we can review it with Tyler. Do you want to take lead on this @zachlatta

**Comment by zachlatta** [comment]
> Do you want to take lead on this @zachlatta

Yeah, sure. You can just ask me to do it. No point in asking if you assign the issue to me :-P.

---

Agreed that it makes sense for us to start this sooner than later. However, do you think this takes priority over our current objectives (fundraising/club in a box)? Perhaps I could do this in July after we close our "round"?

> We should initially figure out what all the forms are and everything, then setup a time with Tyler write it together.

I don't know if it's fair of us to ask @TylerMenezes to write it with us. From what I've heard, it's an enormous time commitment (~8 hours). Perhaps we could have him skim over a draft instead?

**Comment by jonleung** [comment]
Agreed for July.

Tyler specifically said multiple times that he wanted to go through it with
us and it would only take a couple hours.


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by tylermenezes** [comment]
I'm happy to help write a first draft. Can you guys go through it quickly yourself and answer the questions which are obvious?

I think most questions in parts I through VIII are pretty obvious ("Do you or will you engage in economic development?", "Are you submitting this application more than 27 months after the end of the month in which you were legally formed?", etc) That part shouldn't take more than an hour at most. If you aren't sure about any questions leave it and we can go through it together.

**Comment by jonleung** [comment]
:thumbsup:

That sounds good @TylerMenezes, thanks!


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by zachlatta** [comment]
Moving to hackedu/meta#38.
